apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  HTTP_PORT: "8080"
  HTTPS_PORT: "8443"
  index.html: |
    <!doctype html>
    <html lang="ru">
    <head>
      <meta charset="utf-8">
      <title>Netology Kubernetes</title>
    </head>
    <body>
      <h1>Netology Kubernetes</h1>
      <p>Страница отдается из ConfigMap.</p>
    </body>
    </html>
