apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: netology-student-pod-log-reader
  namespace: kuber-2-4
subjects:
  - kind: User
    name: netology-student
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-log-reader
  apiGroup: rbac.authorization.k8s.io
