apiVersion: v1
kind: Service
metadata:
  name: {{ include "netology-app.fullname" . }}-frontend
  labels:
    {{- include "netology-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
