{
 "title": "Netology Node Exporter",
 "tags": [
  "netology",
  "nodeexporter"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU utilization, %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent", "label": "100 - idle" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU used {{instance}}"
    }
   ]
  },
  {
   "title": "CPULA 1 / 5 / 15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "load average" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexporter\"}",
     "legendFormat": "load1 {{instance}}"
    },
    {
     "expr": "node_load5{job=\"nodeexporter\"}",
     "legendFormat": "load5 {{instance}}"
    },
    {
     "expr": "node_load15{job=\"nodeexporter\"}",
     "legendFormat": "load15 {{instance}}"
    }
   ]
  },
  {
   "title": "Free memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes", "label": "MemAvailable" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"nodeexporter\"}",
     "legendFormat": "available memory {{instance}}"
    }
   ]
  },
  {
   "title": "Filesystem free space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes", "label": "available bytes" }
   ],
   "targets": [
    {
     "expr": "max by(instance) (node_filesystem_avail_bytes{job=\"nodeexporter\",fstype!~\"tmpfs|fuse.*|overlay|squashfs|rootfs\"})",
     "legendFormat": "minimum free filesystem {{instance}}"
    }
   ]
  }
 ]
}